-- Phase 234 (Allocation Exception Queue audit #234) — new AdminTaskKind so the
-- `orders.master.exception` consumer can raise a dedicated ops task when a
-- verified order can't be routed and is parked in EXCEPTION_QUEUE. Keyed like
-- COD_COLLECTION_OVERDUE / CHARGEBACK_EVIDENCE_DUE (no first-class order
-- LedgerSourceType): unique on (kind, sourceType=MANUAL, sourceId=masterOrderId)
-- via the existing admin_tasks (kind, source_type, source_id) unique index.
-- Not yet applied (branch sd001); deploy with `prisma migrate deploy`.
--
-- (ADD VALUE only — not used elsewhere in this migration, so it is
-- transaction-safe on PG 12+.)
ALTER TYPE "AdminTaskKind" ADD VALUE IF NOT EXISTS 'ORDER_ALLOCATION_EXCEPTION';
