export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  SELLER = 'SELLER',
  SELLER_STAFF = 'SELLER_STAFF',
  ADMIN = 'ADMIN',
  SUPPORT = 'SUPPORT',
  AFFILIATE = 'AFFILIATE',
  FRANCHISE = 'FRANCHISE',
}
