export const SELLER_EVENTS = {
  REGISTERED: 'seller.registered',
  LOGGED_IN: 'seller.logged_in',
  LOGIN_FAILED: 'seller.login_failed',
  ACCOUNT_LOCKED: 'seller.account_locked',
  PASSWORD_RESET_REQUESTED: 'seller.password_reset_requested',
  PASSWORD_RESET_COMPLETED: 'seller.password_reset_completed',
  ONBOARDING_SUBMITTED: 'seller.onboarding.submitted',
  ONBOARDING_APPROVED: 'seller.onboarding.approved',
  ONBOARDING_REJECTED: 'seller.onboarding.rejected',
  STATUS_ACTIVATED: 'seller.status.activated',
  STATUS_SUSPENDED: 'seller.status.suspended',
  PROFILE_UPDATED: 'seller.profile_updated',
  MEDIA_UPLOADED: 'seller.media_uploaded',
  MEDIA_DELETED: 'seller.media_deleted',
  STATUS_CHANGED: 'seller.status_changed',
  BANK_UPDATED: 'seller.bank.updated',
  PICKUP_ADDRESS_UPDATED: 'seller.pickup_address.updated',
} as const;
