/**
 * Phase 194 (Faceted Filters audit) — locks the genuine remediations:
 *
 *   #9  facets fan out (all configs computed in one pass)
 *   #12 active BUILT-IN selections (brand / price) propagate into every
 *       OTHER facet's conditions (disjunctive faceting was metafield-only)
 *   #13 price bounds returned as Decimal-precise strings
 *   #18 computePriceRange returns null only for an empty result set, NOT
 *       for a legitimate all-free-products (min=max=0) set
 *   #19 isAutoGenerated flag on auto-synthesized configs
 *   #20 computeTextMetafieldFacets json branch excludes value_text rows
 *       so a dual-populated row isn't double-counted
 */

import { Prisma } from '@prisma/client';
import { StorefrontFiltersController } from './storefront-filters.controller';
import { PrismaStorefrontRepository } from '../../../infrastructure/repositories/prisma-storefront.repository';

// Prisma.Sql exposes `.sql` (parametrized text) in current versions; fall
// back to joining `.strings` for resilience across minor versions.
const sqlText = (s: any): string =>
  s == null ? '' : typeof s.sql === 'string' ? s.sql : Array.isArray(s.strings) ? s.strings.join('?') : String(s);

const anyConditionMentions = (conditions: any[], needle: string): boolean =>
  conditions.some((c) => sqlText(c).includes(needle));

describe('StorefrontFiltersController — Phase 194 faceting', () => {
  function makeController(overrides: Partial<Record<string, any>> = {}) {
    const storefrontRepo = {
      findFilterConfigs: jest.fn().mockResolvedValue([]), // no manual overrides
      findFilterableDefinitions: jest.fn().mockResolvedValue([
        {
          id: 'def-size',
          key: 'size',
          name: 'Size',
          type: 'SINGLE_SELECT',
          choices: [{ value: 'L', label: 'Large' }],
          namespace: 'custom',
          ownerType: 'PRODUCT',
          categoryId: 'cat1',
        },
      ]),
      findCollectionProductCategoryIds: jest.fn().mockResolvedValue([]),
      computeBrandFacets: jest.fn().mockResolvedValue([{ value: 'b1', label: 'Nike', count: 5 }]),
      computePriceRange: jest.fn().mockResolvedValue({ min: '500', max: '2000' }),
      computeAvailabilityFacets: jest.fn().mockResolvedValue({ in_stock: 10, out_of_stock: 2 }),
      computeBooleanMetafieldFacets: jest.fn().mockResolvedValue([]),
      computeNumericMetafieldRange: jest.fn().mockResolvedValue(null),
      computeTextMetafieldFacets: jest.fn().mockResolvedValue([{ value: 'L', count: 3 }]),
      ...overrides,
    };
    const categoryRepo = {
      findAncestorIds: jest.fn().mockResolvedValue(['cat1']),
    };
    const cache = {
      // invoke the factory directly — bypasses Redis
      getOrSetFilters: jest.fn((_key: unknown, fn: () => Promise<unknown>) => fn()),
    };
    const filterValidator = {
      // brand is actively selected
      scrub: jest.fn().mockResolvedValue(new Map<string, string[]>([['brand', ['b1']]])),
    };
    const controller = new StorefrontFiltersController(
      storefrontRepo as any,
      categoryRepo as any,
      cache as any,
      filterValidator as any,
    );
    return { controller, storefrontRepo, categoryRepo, cache, filterValidator };
  }

  const req = { query: { 'filter[brand]': 'b1' } } as any;

  it('#9 fans out every configured facet in one response (brand, price, availability, size)', async () => {
    const { controller } = makeController();
    const res = await controller.getFilters(req, 'cat1');
    const keys = (res.data as any).filters.map((f: any) => f.key);
    expect(keys).toEqual(expect.arrayContaining(['brand', 'price_range', 'availability', 'size']));
    expect((res.data as any).filters).toHaveLength(4);
  });

  it('#12 propagates the active brand selection into the price facet conditions', async () => {
    const { controller, storefrontRepo } = makeController();
    await controller.getFilters(req, 'cat1');
    // computePriceRange(baseConditions, otherConditions) — brand must appear
    // in otherConditions (price excludes itself, not brand).
    const otherConditions = storefrontRepo.computePriceRange.mock.calls[0][1];
    expect(anyConditionMentions(otherConditions, 'brand_id')).toBe(true);
  });

  it('#12 propagates the active brand selection into the metafield (size) facet conditions', async () => {
    const { controller, storefrontRepo } = makeController();
    await controller.getFilters(req, 'cat1');
    const allConditions = storefrontRepo.computeTextMetafieldFacets.mock.calls[0][1];
    expect(anyConditionMentions(allConditions, 'brand_id')).toBe(true);
  });

  it('#12 does NOT self-filter the brand facet by the active brand', async () => {
    const { controller, storefrontRepo } = makeController();
    await controller.getFilters(req, 'cat1');
    const otherConditions = storefrontRepo.computeBrandFacets.mock.calls[0][1];
    expect(anyConditionMentions(otherConditions, 'brand_id')).toBe(false);
  });

  it('#13 returns price bounds as strings (money on the wire)', async () => {
    const { controller } = makeController();
    const res = await controller.getFilters(req, 'cat1');
    const price = (res.data as any).filters.find((f: any) => f.key === 'price_range');
    expect(price.range).toEqual({ min: '500', max: '2000' });
    expect(typeof price.range.min).toBe('string');
  });

  it('#19 marks auto-synthesized configs with isAutoGenerated=true', async () => {
    const { controller } = makeController();
    const res = await controller.getFilters(req, 'cat1');
    for (const f of (res.data as any).filters) {
      expect(f.isAutoGenerated).toBe(true);
    }
  });
});

describe('PrismaStorefrontRepository — Phase 194 raw SQL fixes', () => {
  function makeRepo(queryResult: unknown) {
    const $queryRaw = jest.fn().mockResolvedValue(queryResult);
    const repo = new PrismaStorefrontRepository({ $queryRaw } as any);
    return { repo, $queryRaw };
  }

  it('#18 returns null when there are no matching products (NULL bounds)', async () => {
    const { repo } = makeRepo([{ min: null, max: null }]);
    await expect(repo.computePriceRange([], [])).resolves.toBeNull();
  });

  it('#18 does NOT return null for a legitimate all-free-products set (min=max=0)', async () => {
    const { repo } = makeRepo([{ min: '0', max: '0' }]);
    await expect(repo.computePriceRange([], [])).resolves.toEqual({ min: '0', max: '0' });
  });

  it('#13 returns price bounds as strings', async () => {
    const { repo } = makeRepo([{ min: '500', max: '2000' }]);
    const range = await repo.computePriceRange([], []);
    expect(range).toEqual({ min: '500', max: '2000' });
    expect(typeof range!.min).toBe('string');
  });

  it('#20 json branch of the text-facet union excludes value_text rows (no double-count)', async () => {
    const { repo, $queryRaw } = makeRepo([]);
    await repo.computeTextMetafieldFacets('size', [Prisma.sql`1 = 1`]);
    const sentSql = (typeof $queryRaw.mock.calls[0][0].sql === 'string'
      ? $queryRaw.mock.calls[0][0].sql
      : $queryRaw.mock.calls[0][0].strings.join(' ')) as string;
    expect(sentSql).toContain('UNION ALL');
    expect(sentSql).toContain('value_text IS NULL');
  });
});
