// Phase 19 GST — HTML templates for tax documents.
//
// These templates are CA-DRAFT. Engineering ships a complete renderer
// shape (every CBIC-required field in the right zones) but final
// styling, supplier-side logos, and per-template legal disclaimers
// are pending CA sign-off. The template is intentionally inline-styled
// + minimal CSS so HTML→PDF renderers don't have layout surprises.
//
// One pure function per document-type bucket:
//   renderInvoiceHtml      — TAX_INVOICE / INVOICE_CUM_BILL_OF_SUPPLY
//   renderBillOfSupplyHtml — BILL_OF_SUPPLY (composition / exempt)
//   renderCreditNoteHtml   — CREDIT_NOTE
//   renderDebitNoteHtml    — DEBIT_NOTE
//   renderLegacyReceiptHtml— LEGACY_RECEIPT (non-tax, pre-GST history)
//
// All HTML is escaped via `e()`. No DB / Prisma I/O.

import type {
  TaxDocument,
  TaxDocumentLine,
  Prisma,
} from '@prisma/client';

export type TaxTemplateMode = 'OFF' | 'AUDIT' | 'STRICT';

export interface TemplateInput {
  /** Phase 23 — mode-aware DRAFT banner. Default 'OFF' (banner ON) so
   *  pre-Phase-23 callers don't change behaviour. The PDF service
   *  threads the resolved `TaxModeService.getMode()` value through. */
  mode?: TaxTemplateMode;
  document: Pick<
    TaxDocument,
    | 'documentNumber'
    | 'documentType'
    | 'financialYear'
    | 'invoiceType'
    | 'generatedAt'
    | 'supplierGstin'
    | 'sellerLegalName'
    | 'sellerAddressJson'
    | 'sellerStateCode'
    | 'buyerGstin'
    | 'buyerLegalName'
    | 'billingAddressJson'
    | 'shippingAddressJson'
    | 'placeOfSupplyStateCode'
    | 'reverseChargeApplicable'
    | 'reverseChargeReason'
    | 'taxableAmountInPaise'
    | 'cgstAmountInPaise'
    | 'sgstAmountInPaise'
    | 'igstAmountInPaise'
    | 'totalTaxAmountInPaise'
    | 'cessAmountInPaise'
    | 'roundOffAmountInPaise'
    | 'documentTotalInPaise'
    | 'amountInWords'
    | 'currencyCode'
    | 'paymentMode'
    | 'originalDocumentNumber'
    | 'reason'
    // Phase 22 e-invoice metadata — required on the printed invoice
    // per CBIC GST e-invoicing spec when the document was IRP-signed.
    // Nullable on documents that aren't e-invoice-applicable (B2C,
    // sub-threshold, BILL_OF_SUPPLY).
    | 'irn'
    | 'ackNo'
    | 'ackDate'
    | 'qrCodeUrl'
    | 'einvoiceStatus'
  > &
    // Marketplace order reference for the invoice header. Optional so
    // synthetic callers (tests) can omit it; real TaxDocument rows carry it.
    Partial<Pick<TaxDocument, 'masterOrderId' | 'subOrderId'>>;
  lines: Array<
    Pick<
      TaxDocumentLine,
      | 'lineNumber'
      | 'productName'
      | 'sku'
      | 'hsnOrSacCode'
      | 'uqcCode'
      | 'quantity'
      | 'unitPriceInPaise'
      | 'discountAmountInPaise'
      | 'taxableAmountInPaise'
      | 'gstRateBps'
      | 'cgstAmountInPaise'
      | 'sgstAmountInPaise'
      | 'igstAmountInPaise'
      | 'cessAmountInPaise'
      | 'lineTotalInPaise'
    > &
      // lineType drives the products-vs-charges split. Optional so callers
      // that omit it have their lines treated as products.
      Partial<Pick<TaxDocumentLine, 'lineType'>>
  >;
}

/**
 * Seller product tax invoice (TAX_INVOICE / INVOICE_CUM_BILL_OF_SUPPLY).
 *
 * The marketplace issues this on the seller's behalf, so the supplier is
 * the seller and the recipient is the customer. Standalone (does not use
 * baseEnvelope) so the seller invoice can carry every CBIC field in a
 * professional layout: seller + buyer + shipping parties, marketplace
 * order reference, itemised products (with per-line discount), a separate
 * Other Charges block (shipping / gift-wrap / convenience / COD fee — these
 * arrive as non-PRODUCT TaxDocumentLine rows), the CGST/SGST/IGST tax
 * summary, amount in words, the e-invoice (IRN/QR) block, and the
 * "generated by Sportsmart.com on behalf of the seller" declaration.
 *
 * Numbering is already seller-wise + FY-wise (DocumentSequenceService keys
 * by supplierGstin + financialYear; tax_documents enforces the unique).
 */
export function renderInvoiceHtml(input: TemplateInput): string {
  const d = input.document;
  const title =
    d.documentType === 'INVOICE_CUM_BILL_OF_SUPPLY'
      ? 'Invoice-cum-Bill of Supply'
      : 'Tax Invoice';

  const showDraft = (input.mode ?? 'OFF') !== 'STRICT';
  const draftBanner = showDraft
    ? `
    <div style="background:#fff3cd; border:1px solid #ffeeba; color:#856404;
                padding:8px 12px; margin-bottom:12px; font-size:11px;">
      <strong>DRAFT</strong> — Template pending CA sign-off. Layout, supplier
      branding, and legal disclaimers are not final. Not for issuance to customers.
    </div>`
    : '';

  const supplierAddr = formatAddress(d.sellerAddressJson as Prisma.JsonValue | null);
  const billingAddr = formatAddress(d.billingAddressJson as Prisma.JsonValue | null);
  const shippingAddr = formatAddress(d.shippingAddressJson as Prisma.JsonValue | null);

  // Charges (shipping / gift-wrap / convenience / COD) arrive as
  // non-PRODUCT lines. ROUND_OFF / DISCOUNT_ADJUSTMENT are reflected in the
  // totals, not shown as charge lines. A line with no lineType (e.g. a
  // synthetic caller) is treated as a product.
  const isCharge = (lt: unknown): boolean =>
    !!lt && lt !== 'PRODUCT' && lt !== 'ROUND_OFF' && lt !== 'DISCOUNT_ADJUSTMENT';
  const productLines = input.lines.filter((l) => !isCharge(l.lineType));
  const chargeLines = input.lines.filter((l) => isCharge(l.lineType));

  const CHARGE_LABEL: Record<string, string> = {
    SHIPPING: 'Shipping &amp; Handling',
    GIFT_WRAP: 'Gift Wrap',
    CONVENIENCE_FEE: 'Convenience Fee',
    COD_FEE: 'Cash-on-Delivery Fee',
  };

  const lineGst = (l: TemplateInput['lines'][number]): bigint =>
    l.cgstAmountInPaise + l.sgstAmountInPaise + l.igstAmountInPaise + l.cessAmountInPaise;

  const productRows = productLines
    .map(
      (l, i) => `<tr>
      <td>${i + 1}</td>
      <td>${e(l.productName)}${l.sku ? `<br /><small style="color:#6b7280;">SKU: ${e(l.sku)}</small>` : ''}</td>
      <td>${e(l.hsnOrSacCode ?? '—')}</td>
      <td>${e(l.uqcCode ?? '—')}</td>
      <td class="r">${e(decimalToString(l.quantity))}</td>
      <td class="r">${paiseToRupees(l.unitPriceInPaise)}</td>
      <td class="r">${paiseToRupees(l.discountAmountInPaise)}</td>
      <td class="r">${paiseToRupees(l.taxableAmountInPaise)}</td>
      <td class="r">${(l.gstRateBps / 100).toFixed(2)}</td>
      <td class="r">${paiseToRupees(lineGst(l))}</td>
      <td class="r">${paiseToRupees(l.lineTotalInPaise)}</td>
    </tr>`,
    )
    .join('\n');

  const chargeRows = chargeLines
    .map(
      (l) => `<tr>
      <td>${CHARGE_LABEL[l.lineType as string] ?? e(l.productName)}</td>
      <td>${e(l.hsnOrSacCode ?? '—')}</td>
      <td class="r">${paiseToRupees(l.taxableAmountInPaise)}</td>
      <td class="r">${(l.gstRateBps / 100).toFixed(2)}</td>
      <td class="r">${paiseToRupees(lineGst(l))}</td>
      <td class="r">${paiseToRupees(l.lineTotalInPaise)}</td>
    </tr>`,
    )
    .join('\n');

  const chargesSection = chargeLines.length
    ? `
  <h2 class="sec">Other Charges</h2>
  <table class="lines">
    <thead><tr>
      <th>Charge</th><th>SAC</th>
      <th class="r">Taxable (₹)</th><th class="r">GST %</th>
      <th class="r">GST (₹)</th><th class="r">Amount (₹)</th>
    </tr></thead>
    <tbody>${chargeRows}</tbody>
  </table>`
    : '';

  const orderRefRows = d.masterOrderId
    ? `<tr>
        <td class="k">Marketplace Order ID:</td><td>${e(d.masterOrderId)}</td>
        <td class="k">Sub-order ID:</td><td>${e(d.subOrderId ?? '—')}</td>
      </tr>`
    : '';

  const reverseChargeRow = d.reverseChargeApplicable
    ? `<tr><td class="k">Reverse Charge:</td><td colspan="3"><strong>YES</strong> — ${e(d.reverseChargeReason ?? '')}</td></tr>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${e(title)} — ${e(d.documentNumber)}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
           font-size: 11px; color: #1f2937; margin: 24px; line-height: 1.45; }
    .brandbar { display: flex; justify-content: space-between; align-items: flex-end;
                border-bottom: 3px solid #e11d2a; padding-bottom: 8px; }
    .brand { font-size: 22px; font-weight: 800; letter-spacing: 0.5px; color: #0F1115; }
    .brand span { color: #e11d2a; }
    h1 { font-size: 20px; margin: 0; color: #0F1115; }
    .behalf { font-size: 10px; color: #6b7280; margin: 4px 0 12px; }
    h2.sec { font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.04em;
             color: #374151; margin: 16px 0 6px; border-left: 3px solid #e11d2a; padding-left: 8px; }
    table { width: 100%; border-collapse: collapse; }
    table.head td { border: none; padding: 2px 6px; vertical-align: top; }
    table.head td.k { text-align: right; color: #6b7280; width: 18%; white-space: nowrap; }
    .meta { display: flex; gap: 16px; margin-top: 10px; }
    .party { flex: 1; border: 1px solid #d1d5db; border-radius: 6px; padding: 8px 10px; min-height: 92px; }
    .party h3 { margin: 0 0 4px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.03em; color: #6b7280; }
    table.lines { margin-top: 6px; }
    table.lines th, table.lines td { border: 1px solid #d1d5db; padding: 5px 7px; text-align: left; vertical-align: top; }
    table.lines th { background: #f3f4f6; font-weight: 600; }
    .r { text-align: right; white-space: nowrap; font-variant-numeric: tabular-nums; }
    .totals { width: 56%; margin-left: auto; margin-top: 10px; }
    .totals td { border: none; padding: 2px 6px; }
    .totals td.k { text-align: right; color: #374151; }
    .totals td.v { text-align: right; font-variant-numeric: tabular-nums; }
    .totals tr.grand td { border-top: 2px solid #0F1115; font-weight: 800; font-size: 13px; padding-top: 5px; }
    .words { margin-top: 8px; font-size: 11px; }
    .declaration { margin-top: 18px; border: 1px solid #d1d5db; border-radius: 6px; padding: 10px 12px;
                   display: flex; justify-content: space-between; gap: 16px; }
    .declaration .body { font-size: 10px; color: #4b5563; }
    .sign { text-align: center; font-size: 10px; color: #4b5563; min-width: 180px; }
    .sign .line { margin-top: 32px; border-top: 1px solid #9ca3af; padding-top: 4px; }
    .footer { margin-top: 14px; padding-top: 6px; border-top: 1px solid #e5e7eb; font-size: 9px; color: #6b7280; }
  </style>
</head>
<body>
  ${draftBanner}
  <div class="brandbar">
    <div>
      <div class="brand">SPORTSMART<span>.com</span></div>
    </div>
    <h1>${e(title)}</h1>
  </div>
  <div class="behalf">Tax invoice issued by Sportsmart.com on behalf of the seller named below.</div>

  <table class="head">
    <tr>
      <td class="k">Invoice No:</td><td><strong>${e(d.documentNumber)}</strong></td>
      <td class="k">Invoice Date:</td><td>${formatDate(d.generatedAt)}</td>
    </tr>
    <tr>
      <td class="k">Financial Year:</td><td>${e(d.financialYear)}</td>
      <td class="k">Invoice Type:</td><td>${e(d.invoiceType ?? '—')}</td>
    </tr>
    ${orderRefRows}
    ${reverseChargeRow}
  </table>

  <div class="meta">
    <div class="party">
      <h3>Seller (Supplier)</h3>
      <div><strong>${e(d.sellerLegalName ?? '—')}</strong></div>
      <div>${supplierAddr}</div>
      <div>GSTIN: <strong>${e(d.supplierGstin ?? '—')}</strong></div>
      <div>State Code: ${e(d.sellerStateCode ?? '—')}</div>
    </div>
    <div class="party">
      <h3>Buyer (Billed To)</h3>
      <div><strong>${e(d.buyerLegalName ?? '—')}</strong></div>
      <div>${billingAddr}</div>
      <div>GSTIN: <strong>${e(d.buyerGstin ?? '—')}</strong></div>
      <div>Place of Supply: ${e(d.placeOfSupplyStateCode ?? '—')}</div>
    </div>
    <div class="party">
      <h3>Shipped To</h3>
      <div>${shippingAddr || billingAddr || '—'}</div>
    </div>
  </div>

  <h2 class="sec">Item Details</h2>
  <table class="lines">
    <thead><tr>
      <th style="width:24px;">#</th>
      <th>Description</th>
      <th>HSN</th>
      <th>UQC</th>
      <th class="r">Qty</th>
      <th class="r">Rate (₹)</th>
      <th class="r">Discount (₹)</th>
      <th class="r">Taxable (₹)</th>
      <th class="r">GST %</th>
      <th class="r">GST (₹)</th>
      <th class="r">Total (₹)</th>
    </tr></thead>
    <tbody>${productRows}</tbody>
  </table>

  ${chargesSection}

  <h2 class="sec">Tax Summary</h2>
  <table class="totals">
    <tr><td class="k">Taxable Value:</td><td class="v">${paiseToRupees(d.taxableAmountInPaise)}</td></tr>
    <tr><td class="k">CGST:</td><td class="v">${paiseToRupees(d.cgstAmountInPaise)}</td></tr>
    <tr><td class="k">SGST:</td><td class="v">${paiseToRupees(d.sgstAmountInPaise)}</td></tr>
    <tr><td class="k">IGST:</td><td class="v">${paiseToRupees(d.igstAmountInPaise)}</td></tr>
    <tr><td class="k">Cess:</td><td class="v">${paiseToRupees(d.cessAmountInPaise)}</td></tr>
    <tr><td class="k">Total GST:</td><td class="v">${paiseToRupees(d.totalTaxAmountInPaise)}</td></tr>
    ${Number(d.roundOffAmountInPaise) !== 0 ? `<tr><td class="k">Round Off:</td><td class="v">${paiseToRupees(d.roundOffAmountInPaise)}</td></tr>` : ''}
    <tr class="grand"><td class="k">Grand Total:</td><td class="v">${paiseToRupees(d.documentTotalInPaise)}</td></tr>
  </table>
  ${d.amountInWords ? `<div class="words"><em>Amount in words:</em> ${e(d.amountInWords)}</div>` : ''}

  ${renderEinvoiceBlock(d)}

  <div class="declaration">
    <div class="body">
      <strong>Declaration:</strong> Invoice generated by Sportsmart.com on behalf of the seller.<br />
      The seller named above is solely responsible for the goods supplied and the
      correctness of the tax charged. This is a computer-generated document.<br />
      Verify GSTIN authenticity at https://www.gst.gov.in
    </div>
    <div class="sign">
      For ${e(d.sellerLegalName ?? 'Seller')}
      <div class="line">Authorised Signatory</div>
    </div>
  </div>

  <div class="footer">
    Line items: ${productLines.length}${chargeLines.length ? ` · Charges: ${chargeLines.length}` : ''} ·
    Currency: ${e(d.currencyCode)} · Payment mode: ${e(d.paymentMode ?? '—')}
  </div>
</body>
</html>`;
}

export function renderBillOfSupplyHtml(input: TemplateInput): string {
  return baseEnvelope({
    documentTitleHeading: 'Bill of Supply',
    input,
    showGstColumns: false,
    showTaxTotals: false,
    footerNote:
      'Bill of Supply issued by a composition / exempt supplier. ' +
      'No GST claim applies. Verify GSTIN authenticity at https://www.gst.gov.in',
  });
}

export function renderCreditNoteHtml(input: TemplateInput): string {
  return baseEnvelope({
    documentTitleHeading: 'Credit Note',
    input,
    showGstColumns: true,
    showTaxTotals: true,
    showOriginalDocumentReference: true,
    footerNote:
      'Credit Note issued under CGST Section 34. Reduces output tax ' +
      'liability for the supplier; recipient must reverse the corresponding ' +
      'ITC if already claimed.',
  });
}

export function renderDebitNoteHtml(input: TemplateInput): string {
  return baseEnvelope({
    documentTitleHeading: 'Debit Note',
    input,
    showGstColumns: true,
    showTaxTotals: true,
    showOriginalDocumentReference: true,
    footerNote:
      'Debit Note issued under CGST Section 34. Adds to output tax ' +
      'liability for the supplier; recipient may claim the corresponding ITC.',
  });
}

export function renderLegacyReceiptHtml(input: TemplateInput): string {
  return baseEnvelope({
    documentTitleHeading: 'Legacy Order Receipt',
    input,
    showGstColumns: false,
    showTaxTotals: false,
    footerNote:
      'NON-TAX RECEIPT — predates the GST module. No GST treatment ' +
      'is claimed; the customer should treat this as a historical ' +
      'transaction record only.',
  });
}

// ── Marketplace commission invoice (SAC 9985) ───────────────────────
//
// Phase 159aa stores the commission invoice as denorm columns on
// SellerSettlement (no TaxDocument row exists), so it can't go through
// `renderHtmlForDocument`. This renderer takes the settlement snapshot
// directly and produces the printable tax invoice the marketplace, as
// the e-commerce operator, owes each seller for the commission charge
// (CBIC §31 / Rule 46). The marketplace is the SUPPLIER; the seller is
// the RECIPIENT. Forward charge — RCM does not apply to operator
// commission, so there is no reverse-charge block.

/** A non-GST adjustment / recovery line on the commission invoice
 *  (penalty, SLA fine, clawback, manual debit, …). Informational —
 *  settled in the payout, not part of the commission tax total. */
export interface CommissionInvoiceAdjustment {
  label: string;
  reason: string;
  amountInPaise: bigint;
}

export interface CommissionInvoiceTemplateInput {
  mode?: TaxTemplateMode;
  invoiceNumber: string;
  invoiceDate: Date | null;
  financialYear: string;
  filingPeriod: string;
  sacCode: string;
  gstRateBps: number;
  /** 'IGST' (inter-state) | 'CGST_SGST' (intra-state) | null (legacy). */
  splitType: string | null;

  // Marketplace — supplier of the commission service (Issued by).
  marketplaceLegalName: string;
  marketplaceGstin: string;
  marketplacePan?: string | null;
  marketplaceStateCode: string;
  marketplaceAddressJson: Prisma.JsonValue | null;

  // Seller — recipient (Issued to). GSTIN null ⇒ B2C (unregistered).
  sellerLegalName: string;
  sellerShopName?: string | null;
  sellerGstin: string | null;
  sellerPan?: string | null;
  sellerIsB2c: boolean;
  sellerStateCode: string | null;
  sellerAddressJson: Prisma.JsonValue | null;
  placeOfSupplyStateCode: string;

  // Settlement context.
  settlementId: string;
  settlementStatementRef?: string | null;
  cyclePeriodStart: Date | null;
  cyclePeriodEnd: Date | null;
  totalOrders?: number;
  totalItems?: number;
  /** Gross GMV for the cycle — drives the effective-commission-rate line. */
  grossGmvInPaise?: bigint;

  // Commission amounts (paise). Taxable = the commission charged; GST on it.
  commissionTaxableInPaise: bigint;
  cgstInPaise: bigint;
  sgstInPaise: bigint;
  igstInPaise: bigint;
  totalGstInPaise: bigint;

  // Non-GST adjustments / recoveries (settled in payout, not taxed here).
  adjustments?: CommissionInvoiceAdjustment[];

  irn?: string | null;
}

export function renderCommissionInvoiceHtml(
  input: CommissionInvoiceTemplateInput,
): string {
  const grandTotalInPaise =
    input.commissionTaxableInPaise + input.totalGstInPaise;
  const ratePct = (input.gstRateBps / 100).toFixed(2);
  const marketplaceAddr = formatAddress(input.marketplaceAddressJson);
  const sellerAddr = formatAddress(input.sellerAddressJson);

  const showDraft = (input.mode ?? 'OFF') !== 'STRICT';
  const draftBanner = showDraft
    ? `
    <div style="background:#fff3cd; border:1px solid #ffeeba; color:#856404;
                padding:8px 12px; margin-bottom:12px; font-size:11px;">
      <strong>DRAFT</strong> — Template pending CA sign-off. Layout, branding,
      and legal disclaimers are not final.
    </div>`
    : '';

  const sellerGstinLine = input.sellerIsB2c
    ? 'GSTIN: <strong>Unregistered (B2C)</strong>'
    : `GSTIN: <strong>${e(input.sellerGstin ?? '—')}</strong>`;

  const splitLabel =
    input.splitType === 'IGST'
      ? 'Inter-state (IGST)'
      : input.splitType === 'CGST_SGST'
        ? 'Intra-state (CGST + SGST)'
        : '—';

  const period =
    input.cyclePeriodStart && input.cyclePeriodEnd
      ? `${formatDate(input.cyclePeriodStart)} → ${formatDate(input.cyclePeriodEnd)}`
      : '—';

  // Effective commission rate = commission / gross GMV (informational).
  const effectiveRate =
    input.grossGmvInPaise && input.grossGmvInPaise > 0n
      ? `${(
          (Number(input.commissionTaxableInPaise) /
            Number(input.grossGmvInPaise)) *
          100
        ).toFixed(2)}% of GMV`
      : '—';

  const adjustmentsSection =
    input.adjustments && input.adjustments.length
      ? `
  <h2 class="sec">Adjustments &amp; Recoveries</h2>
  <p class="muted">Settled in the payout (see settlement statement) — not part of this tax invoice.</p>
  <table class="lines">
    <thead><tr><th>Particulars</th><th>Reason</th><th class="r">Amount (₹)</th></tr></thead>
    <tbody>
      ${input.adjustments
        .map(
          (a) => `<tr>
        <td>${e(a.label)}</td>
        <td>${e(a.reason)}</td>
        <td class="r">${paiseToRupees(a.amountInPaise)}</td>
      </tr>`,
        )
        .join('\n')}
    </tbody>
  </table>`
      : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Commission Tax Invoice — ${e(input.invoiceNumber)}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
           font-size: 11px; color: #1f2937; margin: 24px; line-height: 1.45; }
    .brandbar { display: flex; justify-content: space-between; align-items: flex-end;
                border-bottom: 3px solid #e11d2a; padding-bottom: 8px; }
    .brand { font-size: 22px; font-weight: 800; letter-spacing: 0.5px; color: #0F1115; }
    .brand span { color: #e11d2a; }
    h1 { font-size: 19px; margin: 0; color: #0F1115; }
    .subtitle { font-size: 10px; color: #6b7280; margin: 4px 0 12px; }
    h2.sec { font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.04em;
             color: #374151; margin: 16px 0 6px; border-left: 3px solid #e11d2a; padding-left: 8px; }
    .muted { font-size: 10px; color: #6b7280; margin: 2px 0 4px; }
    table { width: 100%; border-collapse: collapse; }
    table.head td { border: none; padding: 2px 6px; vertical-align: top; }
    table.head td.k { text-align: right; color: #6b7280; width: 16%; white-space: nowrap; }
    .meta { display: flex; gap: 16px; margin-top: 10px; }
    .party { flex: 1; border: 1px solid #d1d5db; border-radius: 6px; padding: 8px 10px; min-height: 96px; }
    .party h3 { margin: 0 0 4px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.03em; color: #6b7280; }
    table.lines { margin-top: 6px; }
    table.lines th, table.lines td { border: 1px solid #d1d5db; padding: 5px 7px; text-align: left; vertical-align: top; }
    table.lines th { background: #f3f4f6; font-weight: 600; }
    .r { text-align: right; white-space: nowrap; font-variant-numeric: tabular-nums; }
    .totals { width: 56%; margin-left: auto; margin-top: 10px; }
    .totals td { border: none; padding: 2px 6px; }
    .totals td.k { text-align: right; color: #374151; }
    .totals td.v { text-align: right; font-variant-numeric: tabular-nums; }
    .totals tr.grand td { border-top: 2px solid #0F1115; font-weight: 800; font-size: 13px; padding-top: 5px; }
    .declaration { margin-top: 18px; border: 1px solid #d1d5db; border-radius: 6px; padding: 10px 12px;
                   display: flex; justify-content: space-between; gap: 16px; }
    .declaration .body { font-size: 10px; color: #4b5563; }
    .sign { text-align: center; font-size: 10px; color: #4b5563; min-width: 190px; }
    .sign .line { margin-top: 32px; border-top: 1px solid #9ca3af; padding-top: 4px; }
    .footer { margin-top: 14px; padding-top: 6px; border-top: 1px solid #e5e7eb; font-size: 9px; color: #6b7280; }
  </style>
</head>
<body>
  ${draftBanner}
  <div class="brandbar">
    <div class="brand">SPORTSMART<span>.com</span></div>
    <h1>Commission Tax Invoice</h1>
  </div>
  <div class="subtitle">Marketplace commission — e-commerce operator services (SAC ${e(input.sacCode)}). Invoice generated for marketplace services provided by Sportsmart.com to the seller.</div>

  <table class="head">
    <tr>
      <td class="k">Invoice No:</td><td><strong>${e(input.invoiceNumber)}</strong></td>
      <td class="k">Invoice Date:</td><td>${formatDate(input.invoiceDate)}</td>
    </tr>
    <tr>
      <td class="k">Financial Year:</td><td>${e(input.financialYear)}</td>
      <td class="k">Filing Period:</td><td>${e(input.filingPeriod)}</td>
    </tr>
    <tr>
      <td class="k">Place of Supply:</td><td>${e(input.placeOfSupplyStateCode)}</td>
      <td class="k">Supply Type:</td><td>${e(splitLabel)}</td>
    </tr>
  </table>

  <div class="meta">
    <div class="party">
      <h3>Issued by — Marketplace</h3>
      <div><strong>${e(input.marketplaceLegalName)}</strong></div>
      <div>${marketplaceAddr}</div>
      <div>GSTIN: <strong>${e(input.marketplaceGstin)}</strong></div>
      ${input.marketplacePan ? `<div>PAN: ${e(input.marketplacePan)}</div>` : ''}
      <div>State Code: ${e(input.marketplaceStateCode)}</div>
    </div>
    <div class="party">
      <h3>Issued to — Seller</h3>
      <div><strong>${e(input.sellerLegalName)}</strong>${
        input.sellerShopName && input.sellerShopName !== input.sellerLegalName
          ? `<br /><small style="color:#6b7280;">${e(input.sellerShopName)}</small>`
          : ''
      }</div>
      <div>${sellerAddr}</div>
      <div>${sellerGstinLine}</div>
      ${input.sellerPan ? `<div>PAN: ${e(input.sellerPan)}</div>` : ''}
      <div>State Code: ${e(input.sellerStateCode ?? '—')}</div>
    </div>
  </div>

  <h2 class="sec">Settlement &amp; Orders</h2>
  <table class="head">
    <tr>
      <td class="k">Settlement ID:</td><td>${e(input.settlementId)}</td>
      <td class="k">Settlement Cycle:</td><td>${period}</td>
    </tr>
    <tr>
      <td class="k">Total Orders:</td><td>${input.totalOrders ?? '—'}</td>
      <td class="k">Total Items:</td><td>${input.totalItems ?? '—'}</td>
    </tr>
    <tr>
      <td class="k">Effective Rate:</td><td>${effectiveRate}</td>
      <td class="k">Statement Ref:</td><td>${e(input.settlementStatementRef ?? '—')}</td>
    </tr>
  </table>

  <h2 class="sec">Commission Charges</h2>
  <table class="lines">
    <thead><tr>
      <th style="width:24px;">#</th>
      <th>Particulars</th>
      <th>SAC</th>
      <th class="r">Taxable (₹)</th>
      <th class="r">GST %</th>
      <th class="r">CGST (₹)</th>
      <th class="r">SGST (₹)</th>
      <th class="r">IGST (₹)</th>
      <th class="r">Total (₹)</th>
    </tr></thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>Marketplace Commission — commission charged on settled / delivered orders</td>
        <td>${e(input.sacCode)}</td>
        <td class="r">${paiseToRupees(input.commissionTaxableInPaise)}</td>
        <td class="r">${ratePct}</td>
        <td class="r">${paiseToRupees(input.cgstInPaise)}</td>
        <td class="r">${paiseToRupees(input.sgstInPaise)}</td>
        <td class="r">${paiseToRupees(input.igstInPaise)}</td>
        <td class="r">${paiseToRupees(grandTotalInPaise)}</td>
      </tr>
    </tbody>
  </table>

  <h2 class="sec">Tax Summary</h2>
  <table class="totals">
    <tr><td class="k">Taxable Value:</td><td class="v">${paiseToRupees(input.commissionTaxableInPaise)}</td></tr>
    <tr><td class="k">CGST:</td><td class="v">${paiseToRupees(input.cgstInPaise)}</td></tr>
    <tr><td class="k">SGST:</td><td class="v">${paiseToRupees(input.sgstInPaise)}</td></tr>
    <tr><td class="k">IGST:</td><td class="v">${paiseToRupees(input.igstInPaise)}</td></tr>
    <tr><td class="k">Total GST:</td><td class="v">${paiseToRupees(input.totalGstInPaise)}</td></tr>
    <tr class="grand"><td class="k">Grand Total:</td><td class="v">${paiseToRupees(grandTotalInPaise)}</td></tr>
  </table>

  ${adjustmentsSection}

  ${
    input.irn
      ? `<div style="margin-top:14px; font-size:11px;"><span style="color:#6b7280;">IRN:</span> <code style="word-break:break-all;">${e(input.irn)}</code></div>`
      : ''
  }

  <div class="declaration">
    <div class="body">
      <strong>Note:</strong> This invoice is separate from the seller-to-customer tax invoice.
      It covers only the marketplace services (commission) provided by Sportsmart.com to the seller.<br />
      GST is charged on a forward-charge basis by the marketplace; reverse charge does not apply.
      The seller may claim the GST shown above as input tax credit, subject to eligibility.<br />
      Computer-generated document. Verify GSTIN authenticity at https://www.gst.gov.in
    </div>
    <div class="sign">
      For ${e(input.marketplaceLegalName)}
      <div class="line">Authorised Signatory</div>
    </div>
  </div>

  <div class="footer">
    SAC ${e(input.sacCode)} (e-commerce operator commission) · ${e(splitLabel)} · Settlement ${e(input.settlementId)}
  </div>
</body>
</html>`;
}

// ── Settlement / payout statement ───────────────────────────────────
//
// NOT a tax invoice — a remittance advice that reconciles a seller's
// payout for one settlement: Gross GMV → less commission → less
// commission GST → less TCS → less TDS → net payout. The commission GST
// itself is documented by the separate commission tax invoice
// (renderCommissionInvoiceHtml); this statement cross-references it.
// Net mirrors SettlementTds194OHookService.computeNetPayoutInPaise.

export interface SettlementStatementOrderLine {
  orderNumber: string;
  date: Date | null;
  productTitle: string;
  quantity: number;
  grossInPaise: bigint;
  commissionInPaise: bigint;
  status: string;
}

export interface SettlementStatementAdjustment {
  label: string;
  reason: string;
  amountInPaise: bigint;
}

export interface SettlementStatementTemplateInput {
  mode?: TaxTemplateMode;
  statementRef: string;
  settlementId?: string;
  statementDate: Date | null;
  periodStart: Date | null;
  periodEnd: Date | null;
  payoutDate?: Date | null;
  status: string;
  totalOrders?: number;
  totalItems?: number;

  // Marketplace — the payer.
  marketplaceLegalName: string;
  marketplaceGstin: string;
  marketplaceStateCode: string;
  marketplaceAddressJson: Prisma.JsonValue | null;

  // Seller — the payee.
  sellerLegalName: string;
  sellerShopName?: string | null;
  sellerGstin: string | null;
  sellerPan?: string | null;
  sellerCode?: string | null;
  sellerStateCode: string | null;
  sellerAddressJson: Prisma.JsonValue | null;

  // Order-level detail (from the settlement's commission records).
  orders?: SettlementStatementOrderLine[];
  returnedOrderCount?: number;

  // Amounts (paise).
  grossGmvInPaise: bigint;
  commissionInPaise: bigint;
  settlementAmountInPaise: bigint;
  commissionGstInPaise: bigint;
  commissionGstSplitType: string | null;
  cgstOnCommissionInPaise: bigint;
  sgstOnCommissionInPaise: bigint;
  igstOnCommissionInPaise: bigint;
  commissionGstRateBps: number;
  tcsInPaise: bigint;
  tcsRateBps: number;
  tdsInPaise: bigint;
  tdsRateBps: number;
  netPayoutInPaise: bigint;

  // Non-GST adjustments / recoveries (debit/credit/penalty/manual).
  adjustments?: SettlementStatementAdjustment[];

  // Payment — bank + payout + cross-reference to the commission invoice.
  utrReference?: string | null;
  paidAt?: Date | null;
  paymentMethod?: string | null;
  bankAccountHolder?: string | null;
  bankName?: string | null;
  bankIfsc?: string | null;
  bankAccountLast4?: string | null;
  commissionInvoiceNumber?: string | null;
}

export function renderSettlementStatementHtml(
  input: SettlementStatementTemplateInput,
): string {
  const showDraft = (input.mode ?? 'OFF') !== 'STRICT';
  const draftBanner = showDraft
    ? `
    <div style="background:#fff3cd; border:1px solid #ffeeba; color:#856404;
                padding:8px 12px; margin-bottom:12px; font-size:11px;">
      <strong>DRAFT</strong> — Template pending CA sign-off. Layout and branding are not final.
    </div>`
    : '';

  const marketplaceAddr = formatAddress(input.marketplaceAddressJson);
  const sellerAddr = formatAddress(input.sellerAddressJson);
  const period =
    input.periodStart && input.periodEnd
      ? `${formatDate(input.periodStart)} → ${formatDate(input.periodEnd)}`
      : '—';
  const payoutDate = input.payoutDate ?? input.paidAt ?? null;

  // Waterfall row — deduction rows shown only when non-zero, mirroring the
  // on-screen breakdown so the document matches what the seller saw.
  const row = (
    label: string,
    amount: bigint,
    opts: { negative?: boolean; emphasis?: boolean; color?: string; hint?: string } = {},
  ): string => {
    const value = `${opts.negative ? '−' : ''}${paiseToRupees(amount)}`;
    return `<tr${opts.emphasis ? ' style="border-top:1px solid #0F1115; border-bottom:1px solid #0F1115;"' : ''}>
      <td style="padding:5px 8px 5px 0; font-weight:${opts.emphasis ? 700 : 500};">
        ${e(label)}${opts.hint ? `<br /><small style="color:#9ca3af; font-weight:400;">${e(opts.hint)}</small>` : ''}
      </td>
      <td style="padding:5px 0; text-align:right; font-variant-numeric:tabular-nums; font-weight:${opts.emphasis ? 700 : 500}; color:${opts.color ?? '#1f2937'}; white-space:nowrap;">${value}</td>
    </tr>`;
  };

  const hasCommGst = input.commissionGstInPaise > 0n;
  const isSplit = input.commissionGstSplitType === 'CGST_SGST';
  const commGstLabel = `Commission GST @ ${(input.commissionGstRateBps / 100).toFixed(0)}% ${isSplit ? '(CGST + SGST)' : '(IGST)'}`;

  const deductionRows = [
    hasCommGst
      ? row(commGstLabel, input.commissionGstInPaise, {
          negative: true,
          color: '#b91c1c',
          hint: 'GST on the platform commission — claimable as ITC on your GSTR-3B.',
        })
      : '',
    hasCommGst && isSplit
      ? `<tr><td style="padding:2px 8px 2px 16px; color:#6b7280;">— CGST on commission</td><td style="padding:2px 0; text-align:right; color:#6b7280;">${paiseToRupees(input.cgstOnCommissionInPaise)}</td></tr>
         <tr><td style="padding:2px 8px 2px 16px; color:#6b7280;">— SGST on commission</td><td style="padding:2px 0; text-align:right; color:#6b7280;">${paiseToRupees(input.sgstOnCommissionInPaise)}</td></tr>`
      : '',
    input.tcsInPaise > 0n
      ? row(`TCS @ ${(input.tcsRateBps / 100).toFixed(2)}% (Section 52)`, input.tcsInPaise, {
          negative: true,
          color: '#b91c1c',
          hint: 'Collected and remitted to the government; reconcile via GSTR-2A/2B.',
        })
      : '',
    input.tdsInPaise > 0n
      ? row(`TDS @ ${(input.tdsRateBps / 100).toFixed(2)}% (Section 194-O)`, input.tdsInPaise, {
          negative: true,
          color: '#b91c1c',
          hint: 'Income-tax withheld; Form 16A issued by the marketplace.',
        })
      : '',
  ]
    .filter(Boolean)
    .join('\n');

  const ordersSection =
    input.orders && input.orders.length
      ? `
  <h2 class="sec">Orders in this Settlement</h2>
  <table class="lines">
    <thead><tr>
      <th>Order No</th><th>Date</th><th>Product</th>
      <th class="r">Qty</th><th class="r">Gross (₹)</th>
      <th class="r">Commission (₹)</th><th>Status</th>
    </tr></thead>
    <tbody>
      ${input.orders
        .map(
          (o) => `<tr>
        <td>${e(o.orderNumber)}</td>
        <td>${formatDate(o.date)}</td>
        <td>${e(o.productTitle)}</td>
        <td class="r">${o.quantity}</td>
        <td class="r">${paiseToRupees(o.grossInPaise)}</td>
        <td class="r">${paiseToRupees(o.commissionInPaise)}</td>
        <td>${e(o.status)}</td>
      </tr>`,
        )
        .join('\n')}
    </tbody>
  </table>`
      : '';

  const adjustmentsSection =
    input.adjustments && input.adjustments.length
      ? `
  <h2 class="sec">Adjustments &amp; Recoveries</h2>
  <table class="lines">
    <thead><tr><th>Particulars</th><th>Reason</th><th class="r">Amount (₹)</th></tr></thead>
    <tbody>
      ${input.adjustments
        .map(
          (a) => `<tr>
        <td>${e(a.label)}</td><td>${e(a.reason)}</td>
        <td class="r">${paiseToRupees(a.amountInPaise)}</td>
      </tr>`,
        )
        .join('\n')}
    </tbody>
  </table>`
      : '';

  const bankLine =
    input.bankAccountHolder || input.bankAccountLast4 || input.bankIfsc
      ? `<div style="font-size:11px; margin-top:4px;">
           <strong>Bank:</strong> ${e(input.bankAccountHolder ?? '—')}${input.bankName ? ` · ${e(input.bankName)}` : ''}${input.bankIfsc ? ` · IFSC ${e(input.bankIfsc)}` : ''}${input.bankAccountLast4 ? ` · A/C ••••${e(input.bankAccountLast4)}` : ''}
         </div>`
      : '';

  const paymentBlock =
    input.status === 'PAID'
      ? `<div style="margin-top:14px; font-size:11px;">
           <strong>Payment:</strong> Paid${payoutDate ? ` on ${formatDate(payoutDate)}` : ''}${input.utrReference ? ` · UTR ${e(input.utrReference)}` : ''}${input.paymentMethod ? ` · ${e(input.paymentMethod)}` : ''}
         </div>${bankLine}`
      : `<div style="margin-top:14px; font-size:11px; color:#92400e;">
           <strong>Payment:</strong> ${e(input.status)} — not yet disbursed${payoutDate ? ` (due ${formatDate(payoutDate)})` : ''}.
         </div>${bankLine}`;

  const crossRef = input.commissionInvoiceNumber
    ? `<div style="margin-top:6px; font-size:11px; color:#555;">
         Commission GST tax invoice for this settlement: <strong>${e(input.commissionInvoiceNumber)}</strong> (issued separately).
       </div>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Settlement Statement — ${e(input.statementRef)}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 11px; color: #1f2937; margin: 24px; line-height: 1.45; }
    .brandbar { display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 3px solid #e11d2a; padding-bottom: 8px; }
    .brand { font-size: 22px; font-weight: 800; letter-spacing: 0.5px; color: #0F1115; }
    .brand span { color: #e11d2a; }
    h1 { font-size: 19px; margin: 0; color: #0F1115; }
    .subtitle { font-size: 10px; color: #6b7280; margin: 4px 0 12px; }
    h2.sec { font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.04em; color: #374151; margin: 16px 0 6px; border-left: 3px solid #e11d2a; padding-left: 8px; }
    table { width: 100%; border-collapse: collapse; }
    table.head td { border: none; padding: 2px 6px; vertical-align: top; }
    table.head td.label { text-align: right; width: 16%; color: #6b7280; white-space: nowrap; }
    .meta { display: flex; gap: 16px; margin-top: 10px; }
    .party { flex: 1; border: 1px solid #d1d5db; border-radius: 6px; padding: 8px 10px; min-height: 92px; }
    .party h3 { margin: 0 0 4px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.03em; color: #6b7280; }
    table.lines { margin-top: 6px; }
    table.lines th, table.lines td { border: 1px solid #d1d5db; padding: 5px 7px; text-align: left; vertical-align: top; }
    table.lines th { background: #f3f4f6; font-weight: 600; }
    .r { text-align: right; white-space: nowrap; font-variant-numeric: tabular-nums; }
    .breakdown { margin-top: 6px; width: 64%; }
    .footer { margin-top: 16px; padding-top: 6px; border-top: 1px solid #e5e7eb; font-size: 9px; color: #6b7280; }
  </style>
</head>
<body>
  ${draftBanner}
  <div class="brandbar">
    <div class="brand">SPORTSMART<span>.com</span></div>
    <h1>Settlement Statement</h1>
  </div>
  <p class="subtitle">Payout / remittance advice for marketplace settlement — this is NOT a GST tax invoice.</p>

  <table class="head">
    <tr>
      <td class="label">Statement Ref:</td><td><strong>${e(input.statementRef)}</strong></td>
      <td class="label">Status:</td><td>${e(input.status)}</td>
    </tr>
    <tr>
      <td class="label">Settlement ID:</td><td>${e(input.settlementId ?? '—')}</td>
      <td class="label">Statement Date:</td><td>${formatDate(input.statementDate)}</td>
    </tr>
    <tr>
      <td class="label">Cycle:</td><td>${period}</td>
      <td class="label">Payout Date:</td><td>${payoutDate ? formatDate(payoutDate) : '—'}</td>
    </tr>
    <tr>
      <td class="label">Orders / Items:</td><td>${input.totalOrders ?? '—'} / ${input.totalItems ?? '—'}</td>
      <td class="label">Returned:</td><td>${input.returnedOrderCount ?? 0}</td>
    </tr>
  </table>

  <div class="meta">
    <div class="party">
      <h3>Marketplace (Payer)</h3>
      <div><strong>${e(input.marketplaceLegalName)}</strong></div>
      <div>${marketplaceAddr}</div>
      <div>GSTIN: <strong>${e(input.marketplaceGstin)}</strong></div>
      <div>State Code: ${e(input.marketplaceStateCode)}</div>
    </div>
    <div class="party">
      <h3>Seller (Payee)</h3>
      <div><strong>${e(input.sellerLegalName)}</strong>${
        input.sellerShopName && input.sellerShopName !== input.sellerLegalName
          ? `<br /><small style="color:#6b7280;">${e(input.sellerShopName)}</small>`
          : ''
      }</div>
      <div>${sellerAddr}</div>
      <div>GSTIN: <strong>${input.sellerGstin ? e(input.sellerGstin) : 'Unregistered'}</strong></div>
      ${input.sellerPan ? `<div>PAN: ${e(input.sellerPan)}</div>` : ''}
      ${input.sellerCode ? `<div>Seller Code: ${e(input.sellerCode)}</div>` : ''}
      <div>State Code: ${e(input.sellerStateCode ?? '—')}</div>
    </div>
  </div>

  ${ordersSection}

  <h2 class="sec">Payout Breakdown</h2>
  <table class="breakdown">
    <tbody>
      ${row('Gross GMV', input.grossGmvInPaise, { hint: 'Customer-paid amount for delivered orders in this period.' })}
      ${row('Commission (platform fee)', input.commissionInPaise, { negative: true, color: '#b91c1c' })}
      ${row('Settlement amount', input.settlementAmountInPaise, { emphasis: true, hint: 'Gross GMV − commission, before statutory deductions.' })}
      ${deductionRows}
      ${row('Net payout', input.netPayoutInPaise, { emphasis: true, color: '#15803d' })}
    </tbody>
  </table>

  ${adjustmentsSection}

  ${paymentBlock}
  ${crossRef}

  <div class="footer">
    TCS (Section 52) and TDS (Section 194-O) are collected and remitted to the government by the marketplace.
    Commission GST is documented on a separate tax invoice and is claimable as input tax credit.<br />
    This is a computer-generated settlement statement.
  </div>
</body>
</html>`;
}

interface EnvelopeOptions {
  documentTitleHeading: string;
  input: TemplateInput;
  showGstColumns: boolean;
  showTaxTotals: boolean;
  showOriginalDocumentReference?: boolean;
  footerNote: string;
}

function baseEnvelope(opts: EnvelopeOptions): string {
  const { input } = opts;
  const d = input.document;
  const supplierAddr = formatAddress(d.sellerAddressJson as Prisma.JsonValue | null);
  const billingAddr = formatAddress(d.billingAddressJson as Prisma.JsonValue | null);
  const shippingAddr = formatAddress(d.shippingAddressJson as Prisma.JsonValue | null);

  // Phase 23 — DRAFT banner is mode-aware. STRICT mode (CA signed off)
  // suppresses the banner so customer-facing PDFs render clean. OFF /
  // AUDIT modes keep the banner visible so dev / staging PDFs cannot
  // be mistaken for the final document.
  const showDraft = (input.mode ?? 'OFF') !== 'STRICT';
  const draftBanner = showDraft
    ? `
    <div style="background: #fff3cd; border: 1px solid #ffeeba; color: #856404;
                padding: 8px 12px; margin-bottom: 12px; font-size: 11px;
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;">
      <strong>DRAFT</strong> — Template pending CA sign-off. Layout, supplier branding,
      and legal disclaimers are not final. Not for issuance to customers.
    </div>`
    : '';

  const linesRows = input.lines
    .map((l) => renderLineRow(l, opts.showGstColumns))
    .join('\n');

  const lineCount = input.lines.length;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${e(opts.documentTitleHeading)} — ${e(d.documentNumber)}</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 11px;
      color: #222;
      margin: 20px;
      line-height: 1.4;
    }
    h1 { font-size: 18px; margin: 0 0 8px 0; }
    h2 { font-size: 13px; margin: 0 0 4px 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { border: 1px solid #ccc; padding: 4px 6px; text-align: left; vertical-align: top; }
    th { background: #f4f4f5; font-weight: 600; }
    .text-right { text-align: right; }
    .totals { width: 50%; margin-left: auto; margin-top: 8px; }
    .totals td { border: none; padding: 2px 6px; }
    .totals td.label { text-align: right; }
    .totals tr.grand td { border-top: 2px solid #222; font-weight: 700; padding-top: 4px; }
    .meta { display: flex; gap: 16px; margin-top: 8px; }
    .meta-block { flex: 1; border: 1px solid #ccc; padding: 6px 8px; min-height: 80px; }
    .footer { margin-top: 16px; padding-top: 6px; border-top: 1px solid #ccc;
              font-size: 9px; color: #555; }
  </style>
</head>
<body>
  ${draftBanner}
  <h1>${e(opts.documentTitleHeading)}</h1>
  <table class="totals" style="width: 100%; margin-top: 0;">
    <tr>
      <td class="label" style="width: 30%;">Document Number:</td>
      <td><strong>${e(d.documentNumber)}</strong></td>
      <td class="label" style="width: 20%;">Date:</td>
      <td>${formatDate(d.generatedAt)}</td>
    </tr>
    <tr>
      <td class="label">Financial Year:</td>
      <td>${e(d.financialYear)}</td>
      <td class="label">Invoice Type:</td>
      <td>${e(d.invoiceType ?? '—')}</td>
    </tr>
    ${
      opts.showOriginalDocumentReference && d.originalDocumentNumber
        ? `<tr>
             <td class="label">Original Document:</td>
             <td>${e(d.originalDocumentNumber)}</td>
             <td class="label">Reason:</td>
             <td>${e(d.reason ?? '—')}</td>
           </tr>`
        : ''
    }
    ${
      d.reverseChargeApplicable
        ? `<tr>
             <td class="label">Reverse Charge:</td>
             <td colspan="3"><strong>YES</strong> — ${e(d.reverseChargeReason ?? '')}</td>
           </tr>`
        : ''
    }
  </table>

  <div class="meta">
    <div class="meta-block">
      <h2>Supplier</h2>
      <div>${e(d.sellerLegalName ?? '—')}</div>
      <div>${supplierAddr}</div>
      <div>GSTIN: <strong>${e(d.supplierGstin ?? '—')}</strong></div>
      <div>State Code: ${e(d.sellerStateCode ?? '—')}</div>
    </div>
    <div class="meta-block">
      <h2>Billed To</h2>
      <div>${e(d.buyerLegalName ?? '—')}</div>
      <div>${billingAddr}</div>
      <div>GSTIN: <strong>${e(d.buyerGstin ?? '—')}</strong></div>
      <div>Place of Supply: ${e(d.placeOfSupplyStateCode ?? '—')}</div>
    </div>
    <div class="meta-block">
      <h2>Shipped To</h2>
      <div>${shippingAddr}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th style="width: 28px;">#</th>
        <th>Description</th>
        <th>HSN/SAC</th>
        <th>UQC</th>
        <th class="text-right">Qty</th>
        <th class="text-right">Rate (₹)</th>
        <th class="text-right">Taxable (₹)</th>
        ${opts.showGstColumns ? `
          <th class="text-right">Rate %</th>
          <th class="text-right">CGST (₹)</th>
          <th class="text-right">SGST (₹)</th>
          <th class="text-right">IGST (₹)</th>` : ''}
        <th class="text-right">Total (₹)</th>
      </tr>
    </thead>
    <tbody>
      ${linesRows}
    </tbody>
  </table>

  <table class="totals">
    <tr><td class="label">Taxable Value:</td><td class="text-right">${paiseToRupees(d.taxableAmountInPaise)}</td></tr>
    ${
      opts.showTaxTotals
        ? `
      <tr><td class="label">CGST:</td><td class="text-right">${paiseToRupees(d.cgstAmountInPaise)}</td></tr>
      <tr><td class="label">SGST:</td><td class="text-right">${paiseToRupees(d.sgstAmountInPaise)}</td></tr>
      <tr><td class="label">IGST:</td><td class="text-right">${paiseToRupees(d.igstAmountInPaise)}</td></tr>
      <tr><td class="label">Cess:</td><td class="text-right">${paiseToRupees(d.cessAmountInPaise)}</td></tr>
      <tr><td class="label">Total Tax:</td><td class="text-right">${paiseToRupees(d.totalTaxAmountInPaise)}</td></tr>`
        : ''
    }
    ${Number(d.roundOffAmountInPaise) !== 0 ? `<tr><td class="label">Round Off:</td><td class="text-right">${paiseToRupees(d.roundOffAmountInPaise)}</td></tr>` : ''}
    <tr class="grand"><td class="label">Grand Total:</td><td class="text-right">${paiseToRupees(d.documentTotalInPaise)}</td></tr>
    ${
      d.amountInWords
        ? `<tr><td colspan="2" style="padding-top: 8px;"><em>Amount in words:</em> ${e(d.amountInWords)}</td></tr>`
        : ''
    }
  </table>

  ${renderEinvoiceBlock(d)}

  <div class="footer">
    Line items: ${lineCount} · Currency: ${e(d.currencyCode)} · Payment mode: ${e(d.paymentMode ?? '—')}<br />
    ${e(opts.footerNote)}
  </div>
</body>
</html>`;
}

/**
 * Render the e-invoice metadata block (IRN + Ack No + Ack Date + QR code).
 *
 * CBIC e-invoicing spec requires the IRN, Ack number, Ack date, and a
 * scannable QR code to appear on every printed copy of an e-invoice
 * (TAX_INVOICE / INVOICE_CUM_BILL_OF_SUPPLY / CREDIT_NOTE / DEBIT_NOTE
 * that fell into the e-invoice net by turnover + B2B + opt-in gates).
 *
 * The QR encodes the IRP-signed JSON content; recipients scan it to
 * verify document authenticity against the IRP without trusting our
 * PDF rendering. We store the URL the IRP returns (`qrCodeUrl`) at
 * generation time and render an `<img>` here — the PDF rendering
 * engine (Puppeteer / Playwright when wired) fetches it at render
 * time. The image is intentionally a normal `<img>` so the PDF
 * binary embeds the bitmap.
 *
 * Returns an empty string for documents that didn't get an IRN
 * (B2C, sub-threshold sellers, BILL_OF_SUPPLY, LEGACY_RECEIPT).
 */
function renderEinvoiceBlock(d: TemplateInput['document']): string {
  // einvoiceStatus values: NOT_APPLICABLE | PENDING | GENERATED | FAILED |
  // CANCELLED. The full IRN/QR block renders only on GENERATED; for the
  // other in-scope states we render a small status badge (Phase 160 #21)
  // so the customer/seller isn't left guessing why there's no IRN. A
  // NOT_APPLICABLE document (B2C / below-threshold) shows nothing.
  if (d.einvoiceStatus !== 'GENERATED' || !d.irn) {
    const badge = (text: string, bg: string, fg: string): string => `
  <div class="einvoice-badge" style="margin-top:18px; padding:8px 12px; border:1px solid ${fg}33; border-radius:6px; background:${bg}; color:${fg}; font-size:11px; font-weight:600;">
    ${e(text)}
  </div>`;
    switch (d.einvoiceStatus) {
      case 'PENDING':
        return badge('e-Invoice: IRN registration pending with the IRP.', '#fffbeb', '#92400e');
      case 'FAILED':
        return badge('e-Invoice: IRN registration failed — automatic retry in progress.', '#fef2f2', '#b91c1c');
      case 'CANCELLED':
        return badge('e-Invoice: IRN was cancelled (revoked at the IRP).', '#f3f4f6', '#525a65');
      default:
        return ''; // NOT_APPLICABLE — no badge.
    }
  }

  const ackDateFmt = d.ackDate
    ? new Date(d.ackDate).toLocaleString('en-IN', {
        timeZone: 'Asia/Kolkata',
        day: 'numeric',
        month: 'short',
        year: 'numeric',
        hour: 'numeric',
        minute: '2-digit',
      })
    : '—';

  const qrImage = d.qrCodeUrl
    ? `<img src="${e(d.qrCodeUrl)}" alt="IRN QR Code — scan to verify on IRP" width="140" height="140" style="border:1px solid #d0d7de; padding:4px; background:#fff;" />`
    : `<div style="width:140px; height:140px; border:1px dashed #d0d7de; padding:8px; font-size:10px; color:#888; text-align:center; box-sizing:border-box;">QR pending — fetch from IRP if needed</div>`;

  return `
  <div class="einvoice-block" style="margin-top:18px; padding:12px 14px; border:1px solid #d0d7de; border-radius:6px; background:#fafbfc; display:flex; gap:16px; align-items:flex-start;">
    <div style="flex-shrink:0;">
      ${qrImage}
    </div>
    <div style="flex:1; font-size:11px; line-height:1.5;">
      <div style="font-weight:600; margin-bottom:4px; font-size:12px;">e-Invoice (CBIC IRP)</div>
      <div><span style="color:#666;">IRN:</span> <code style="word-break:break-all;">${e(d.irn)}</code></div>
      <div><span style="color:#666;">Ack No:</span> ${e(d.ackNo ?? '—')}</div>
      <div><span style="color:#666;">Ack Date:</span> ${e(ackDateFmt)} IST</div>
      <div style="margin-top:6px; color:#555; font-style:italic;">
        Scan the QR with the GSTN e-Invoice mobile app or any compliant
        scanner to verify this invoice against the Invoice Registration
        Portal (IRP).
      </div>
    </div>
  </div>`;
}

function renderLineRow(
  l: TemplateInput['lines'][number],
  showGst: boolean,
): string {
  const qty = decimalToString(l.quantity);
  const ratePct = (l.gstRateBps / 100).toFixed(2);
  const gstCols = showGst
    ? `
      <td class="text-right">${ratePct}</td>
      <td class="text-right">${paiseToRupees(l.cgstAmountInPaise)}</td>
      <td class="text-right">${paiseToRupees(l.sgstAmountInPaise)}</td>
      <td class="text-right">${paiseToRupees(l.igstAmountInPaise)}</td>`
    : '';
  return `<tr>
    <td>${l.lineNumber}</td>
    <td>${e(l.productName)}${l.sku ? `<br /><small style="color:#666;">SKU: ${e(l.sku)}</small>` : ''}</td>
    <td>${e(l.hsnOrSacCode ?? '—')}</td>
    <td>${e(l.uqcCode ?? '—')}</td>
    <td class="text-right">${e(qty)}</td>
    <td class="text-right">${paiseToRupees(l.unitPriceInPaise)}</td>
    <td class="text-right">${paiseToRupees(l.taxableAmountInPaise)}</td>${gstCols}
    <td class="text-right">${paiseToRupees(l.lineTotalInPaise)}</td>
  </tr>`;
}

// ── Helpers ─────────────────────────────────────────────────────────

/** HTML-escape — minimal but safe. The renderer never injects raw
 *  user-supplied HTML; every interpolated value runs through this. */
function e(value: unknown): string {
  if (value === null || value === undefined) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function paiseToRupees(p: bigint | number): string {
  const big = typeof p === 'bigint' ? p : BigInt(p);
  const negative = big < 0n;
  const abs = negative ? -big : big;
  const whole = abs / 100n;
  const cents = abs % 100n;
  const rupees = `${formatIndianGrouping(whole)}.${cents.toString().padStart(2, '0')}`;
  return negative ? `(${rupees})` : rupees;
}

/** Indian numbering grouping: 1,23,45,678 (lakh/crore). */
function formatIndianGrouping(n: bigint): string {
  const s = n.toString();
  if (s.length <= 3) return s;
  const last3 = s.slice(-3);
  const rest = s.slice(0, -3);
  const groups = [];
  let i = rest.length;
  while (i > 0) {
    const start = Math.max(0, i - 2);
    groups.unshift(rest.slice(start, i));
    i = start;
  }
  return `${groups.join(',')},${last3}`;
}

function formatDate(date: Date | null): string {
  if (!date) return '—';
  const d = new Date(date);
  const istMs = d.getTime() + 5.5 * 60 * 60 * 1000;
  const ist = new Date(istMs);
  const dd = ist.getUTCDate().toString().padStart(2, '0');
  const mm = (ist.getUTCMonth() + 1).toString().padStart(2, '0');
  const yyyy = ist.getUTCFullYear();
  return `${dd}-${mm}-${yyyy}`;
}

function decimalToString(d: Prisma.Decimal | number | null | undefined): string {
  if (d == null) return '0';
  if (typeof d === 'number') return d.toString();
  return (d as Prisma.Decimal).toString();
}

function formatAddress(json: Prisma.JsonValue | null | undefined): string {
  if (!json || typeof json !== 'object') return '';
  const obj = json as Record<string, unknown>;
  const parts: string[] = [];
  for (const key of ['line1', 'line2', 'city', 'state', 'pincode', 'country']) {
    const v = obj[key];
    if (typeof v === 'string' && v.trim()) parts.push(v.trim());
  }
  return e(parts.join(', '));
}

/**
 * Pick the right template for the document type. Throws on unknown
 * type so callers don't silently render an empty page.
 */
export function renderHtmlForDocument(input: TemplateInput): string {
  switch (input.document.documentType) {
    case 'TAX_INVOICE':
    case 'INVOICE_CUM_BILL_OF_SUPPLY':
      return renderInvoiceHtml(input);
    case 'BILL_OF_SUPPLY':
      return renderBillOfSupplyHtml(input);
    case 'CREDIT_NOTE':
      return renderCreditNoteHtml(input);
    case 'DEBIT_NOTE':
      return renderDebitNoteHtml(input);
    case 'LEGACY_RECEIPT':
      return renderLegacyReceiptHtml(input);
    default:
      throw new Error(
        `No template registered for documentType ${input.document.documentType}`,
      );
  }
}
