export const QUEUE_TOKENS = {
  WEBHOOKS: 'QUEUE_WEBHOOKS',
  TRACKING: 'QUEUE_TRACKING',
  SETTLEMENTS: 'QUEUE_SETTLEMENTS',
  NOTIFICATIONS: 'QUEUE_NOTIFICATIONS',
  SEARCH_INDEXING: 'QUEUE_SEARCH_INDEXING',
};
